import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

In [2]:
ls

01 - Creating the features.ipynb
01.2 - Creating the features.ipynb
02 - EDA.ipynb
03 - Modelling - ExtraTreesRegressor.ipynb
03 - Modelling - LinearRegression (hasn't worked yet, autoregression).ipynb
03 - Modelling - LinearRegression.ipynb
03 - Modelling - RandomForestRegressor.ipynb
03 - Modelling - SVM-Copy1.ipynb
03 - Modelling - SVM.ipynb
03 - Modelling - lot of models.ipynb
176-01-bikelocations.csv
176-01-ind_dublinalt.csv
176-01-ind_dublinalt.csv.gz
176-01-sum_dublinalt.csv
2008 machine learning start-Copy1.ipynb
2008 machine learning start-Copy2.ipynb
2008 machine learning start.ipynb
2017-06-25.csv
2017-06.csv
2017-06.ipynb
2017-06_features.csv
2017-06_features_complete.csv
2018-06-20.csv
2018-06-20.ipynb
2018-06-20_features.csv
2018-06-20_features2_test.csv
2018-06-20_features_test.csv
2018-Copy1.ipynb
2018.ipynb
2018_features.csv
2018_portobelloroad.csv
2018_pulled_features.csv
PORTOBELLO ROAD.csv
Untitled.ipynb
all-station-features-march_on.ipynb
all-station-features-march

In [3]:
df = pd.read_csv('2018_pulled_features.csv', index_col='timestamp', parse_dates=True)

In [4]:
df.head()

station_id  bikes  spaces  total_docks  bike_lag  hour  \
timestamp                                                                     
2017-06-01 00:00:01           1      0      31           31         0     0   
2017-06-01 00:00:01          82     22       0           22         4     0   
2017-06-01 00:00:01          81     25      15           40         0     0   
2017-06-01 00:00:01          80     25      15           40         0     0   
2017-06-01 00:00:01           9      0      24           24        28     0   

                     day_of_week  month  weekend  deposit  bike_pull  
timestamp                                                             
2017-06-01 00:00:01            3      6        0        0          0  
2017-06-01 00:00:01            3      6        0       18         22  
2017-06-01 00:00:01            3      6        0       25         25  
2017-06-01 00:00:01            3      6        0       25         26  
2017-06-01 00:00:01            3      6        0      -28          0

In [ ]:
X = df.drop('bike_pull', axis=1)
y = df['bike_pull']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [1]:
heads = ['timestamp','station_id','bikes','spaces','total_docks']

In [6]:
validate_model = pd.read_csv('xxx.csv', names=heads, index_col='timestamp', parse_dates=True )

In [ ]:
validate_model.head()

In [ ]:
validate_model.to_csv('from_tday.csv')

In [11]:
validate_model['bike_lag'] = validate_model['bikes'].shift().fillna(0).astype(int)

In [13]:
validate_model['hour'] = pd.DatetimeIndex(validate_model.index).hour

In [14]:
validate_model['day_of_week'] = pd.DatetimeIndex(validate_model.index).dayofweek

In [15]:
validate_model['month'] = pd.DatetimeIndex(validate_model.index).month

In [16]:
validate_model['deposit'] = validate_model['bikes'].diff().fillna(0).astype(int)

In [17]:
validate_model.head(2)

station_id  bikes  spaces  total_docks  bike_lag  \
timestamp                                                                   
2018-07-26 17:47:19.567         107     26      14           40         0   
2018-07-26 17:47:19.498         104     34       6           40        26   

                         hour  day_of_week  month  deposit  
timestamp                                                   
2018-07-26 17:47:19.567    17            3      7        0  
2018-07-26 17:47:19.498    17            3      7        8

In [18]:
validate_model.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 330 entries, 2018-07-26 17:47:19.567000 to 2018-07-26 17:47:19.549000
Data columns (total 9 columns):
station_id     330 non-null int64
bikes          330 non-null int64
spaces         330 non-null int64
total_docks    330 non-null int64
bike_lag       330 non-null int64
hour           330 non-null int64
day_of_week    330 non-null int64
month          330 non-null int64
deposit        330 non-null int64
dtypes: int64(9)
memory usage: 25.8 KB


In [19]:
validate_model = validate_model.dropna()

In [78]:
validate_model['station_id'] =   validate_model['station_id'].astype(int)
validate_model['bikes'] =   validate_model['bikes'].astype(int)
validate_model['spaces'] =   validate_model['spaces'].astype(int)
validate_model['bike_lag'] =   validate_model['bike_lag'].astype(int)
validate_model['hour'] =   validate_model['hour'].astype(int)
validate_model['day_of_week'] =   validate_model['day_of_week'].astype(int)
validate_model['month'] =   validate_model['month'].astype(int)

In [79]:
validate_model.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3 entries, 2018-07-21 14:52:00 to 2018-07-21 21:22:00
Data columns (total 8 columns):
station_id     3 non-null int64
bikes          3 non-null int64
spaces         3 non-null int64
total_docks    3 non-null int64
bike_lag       3 non-null int64
hour           3 non-null int64
day_of_week    3 non-null int64
month          3 non-null int64
dtypes: int64(8)
memory usage: 216.0 bytes


In [ ]:
X_test.head(2)

In [20]:
clf = RandomForestClassifier(n_estimators=50, n_jobs=-1)

In [23]:
model = clf.fit(X_train, y_train)

In [ ]:
predictions = clf.predict(X_test)

In [9]:
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
             precision    recall  f1-score   support

        -40       0.00      0.00      0.00         1
        -34       0.00      0.00      0.00         1
        -26       0.00      0.00      0.00         1
        -19       0.00      0.00      0.00         8
        -18       0.45      0.19      0.27        26
        -17       0.22      0.03      0.06        63
        -16       0.21      0.07      0.10        58
        -15       0.12      0.06      0.08        54
        -14       0.25      0.08      0.12        76
        -13       0.26      0.09      0.13        81
        -12       0.27      0.10      0.14       114
        -11       0.37      0.13      0.19       174
        -10       0.37      0.15      0.21       232
         -9       0.48      0.23      0.31       391
         -8       0.49      0.23      0.31       522
         -7       0.43      0.1

/Users/neil/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
rfr = RandomForestRegressor(n_estimators=50, random_state=0, n_jobs=-1)

In [11]:
model = rfr.fit(X_train, y_train)

In [12]:
predictions = rfr.predict(X_test)

In [13]:
print(rfr.feature_importances_)

[1.63248827e-04 6.04100959e-01 1.62778274e-03 1.82118473e-04
 3.93814402e-01 6.14534516e-05 2.48977539e-05 2.51376525e-05]


In [18]:
print(predictions)

[0. 0. 1. ... 0. 0. 0.]


In [14]:
errors = abs(predictions - y_test)

In [15]:
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.0 degrees.


In [25]:
i = 0
j = 0
print(len(predictions))
for pred in predictions:
    #print(pred)
    if pred > 5:
        print(pred)
        i = i + 1
    else:
        j = j +1
        
print(i)
print(j)
res = i + j
print(res)
print(len(predictions))



3814173
6.0
5.18
6.0
8.0
6.0
6.0
10.0
7.0
9.0
6.0
6.0
6.0
8.0
7.0
8.0
6.0
6.0
8.0
9.0
6.0
6.0
8.0
8.0
6.0
8.0
6.0
7.0
8.0
6.0
7.0
7.0
6.0
7.0
9.92
6.0
6.0
6.0
6.0
8.0
6.0
6.0
7.0
6.0
6.0
6.0
7.0
7.0
8.02
6.0
6.0
6.0
6.0
8.0
6.0
8.08
6.0
8.0
6.0
6.0
6.0
6.0
6.0
8.0
6.0
7.0
6.0
6.0
8.0
7.0
7.0
6.0
7.6
6.0
8.0
7.0
7.0
7.0
6.0
8.0
8.0
9.04
6.0
6.0
8.0
5.3
8.24
6.0
8.0
6.0
8.0
6.0
6.0
6.0
6.0
8.0
6.0
6.0
8.0
8.0
6.0
6.0
6.0
6.0
6.0
11.62
6.0
10.26
6.0
6.0
18.22
6.0
7.0
6.0
6.0
6.0
6.0
8.0
6.0
6.0
7.0
6.0
6.0
6.0
8.0
8.0
6.0
7.0
7.0
7.0
7.0
6.0
6.0
7.0
6.0
6.0
6.0
6.0
6.0
6.0
7.0
7.0
8.0
6.0
6.0
7.0
6.0
6.0
6.0
7.06
7.0
6.0
8.0
6.0
7.0
6.0
6.0
7.0
7.0
7.0
7.0
6.0
6.0
6.0
8.0
8.0
6.0
9.98
6.0
6.0
7.0
6.0
8.0
6.0
8.0
6.0
7.0
6.0
6.0
6.0
6.0
8.0
6.0
6.0
6.0
7.0
11.48
8.12
6.0
7.0
6.0
6.0
6.0
7.0
8.0
7.0
6.0
8.0
6.0
6.0
6.0
6.0
8.0
6.0
7.0
7.0
6.0
6.0
7.0
6.0
6.0
7.0
6.0
6.0
7.0
6.0
6.0
6.0
6.0
6.0
8.0
5.16
9.92
9.96
7.98
8.0
7.0
6.0
8.0
7.02
6.0
7.06
6.0
7.0
6.0
6.0
7.0
8.0
9.0
8.0
9.0
6.0
6.0


9.02
6.0
8.0
6.0
16.28
8.76
7.88
6.0
7.0
8.0
6.0
6.0
6.0
6.0
10.0
6.0
6.0
6.0
7.0
6.0
6.0
8.0
6.0
6.0
8.0
6.0
6.0
6.0
6.0
8.0
6.0
6.0
6.0
6.0
7.0
6.0
8.0
6.0
6.0
8.0
7.0
7.0
6.0
8.0
6.0
8.0
10.04
8.0
6.0
6.0
6.0
6.0
6.0
7.0
9.0
6.0
6.0
6.0
6.0
7.0
6.0
7.0
6.0
8.0
6.0
9.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
10.0
6.0
7.0
6.0
6.0
7.0
7.0
6.0
8.0
6.0
6.0
9.0
7.0
6.0
6.0
8.0
7.0
8.0
6.0
6.0
6.0
8.0
6.0
6.0
6.0
7.06
6.0
6.0
8.0
6.0
6.0
6.0
6.0
8.0
17.06
6.0
12.92
6.0
6.0
8.0
6.0
8.0
8.0
6.0
10.16
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
7.0
8.0
6.0
15.56
6.0
8.0
6.0
6.0
6.0
8.0
15.08
6.0
7.0
8.0
7.0
6.0
6.0
9.0
7.0
8.0
7.0
6.0
6.0
6.0
7.0
9.42
7.0
6.0
6.0
6.0
6.0
7.0
8.0
7.0
6.0
7.86
8.0
6.0
6.0
6.0
8.0
6.0
6.0
6.0
6.0
6.0
6.0
10.0
6.0
6.0
6.0
8.0
6.0
6.0
6.0
11.0
8.0
7.0
7.0
8.0
6.0
6.0
7.0
6.0
6.0
9.0
7.0
8.0
9.0
10.0
7.94
9.0
6.0
7.0
6.0
6.0
11.0
7.0
6.0
8.0
6.0
9.0
9.0
8.0
6.0
6.0
6.0
6.0
6.0
7.0
6.0
7.0
6.0
7.0
6.0
6.0
6.0
8.0
6.0
6.0
6.0
6.0
6.0
7.0
6.0
7.0
10.46
6.0
6.0
6.0
6.0
8.0
7.0
8.0
7.0
5.14
6.

In [82]:
#print(confusion_matrix(y_test, predictions))


In [81]:
#print(classification_report(y_test, predictions))

In [80]:
print(model.predict(validate_model))

[-4.  0. -1.]


In [ ]:
plt.errorbar(X, y, 0.3, fmt='o', alpha=0.5)
plt.plot(X_train, y_train, '-r')
plt.plot(X_test, y_test, '-k', alpha=0.5)

In [24]:
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

NameError: name 'predictions' is not defined

In [ ]:
confirm = validate_model['deposit']

In [ ]:
validation_to_set = validate_model.drop('deposit', axis=1)

In [ ]:
predictions = model.predict(validation_to_set)