In [1]:
import pandas as pd
import numpy as np

In [2]:
ls

176-01-bikelocations.csv
176-01-ind_dublinalt.csv
176-01-ind_dublinalt.csv.gz
176-01-sum_dublinalt.csv
2008 machine learning start-Copy1.ipynb
2008 machine learning start.ipynb
2017-06.csv
2017-06.ipynb
2017-06_features.csv
2017-06_features_complete.csv
2018-06-20.csv
2018-06-20.ipynb
2018-06-20_features.csv
PORTOBELLO ROAD.csv
all-station-features-march_on.ipynb
all-station-features-march_on.py
all-station-features.ipynb
bikes_2018.csv
f_features.csv
features2.csv
features_ready.csv
fulldata-spoken.ipynb
knn for neil.ipynb
machinestarts-2years_all stations.ipynb
machinestarts.ipynb
machinestarts2.ipynb
pboh-features.ipynb
pboh.ipynb
scattered.ipynb
time_series_features.csv


In [3]:
df = pd.read_csv('2017-06_features_complete.csv', parse_dates=True, index_col='timestamp')

In [5]:
df.head(2)

Unnamed: 0  tfl_id  bikes  spaces  total_docks  deposit  \
timestamp                                                                      
2017-06-01 00:00:01          20       1      0      31           31        0   
2017-06-01 00:00:01          52      82     22       0           22       18   

                     deposit_lag  month  weekday  day  deposit_flag  
timestamp                                                            
2017-06-01 00:00:01            0      6        4    1             0  
2017-06-01 00:00:01            4      6        4    1             1

In [6]:
df.isnull().values.any()

False

In [7]:
if df.isnull().values.any() == True:
    for column in df.columns:
        print(df[column].isnull().values.any())
        print(column)
else:
    print("There are no null values")

There are no null values


In [8]:
#from sklearn.preprocessing import StandardScaler

In [9]:
#scaler = StandardScaler()

In [10]:
#scaler.fit(df.drop('deposit_flag', axis=1))

In [11]:
#scaled_features = scaler.transform(df.drop('deposit_flag', axis=1))

In [12]:
#scaled_features


In [13]:
#df_feat = pd.DataFrame(scaled_features, columns=df.columns[:-1])

In [14]:
#df_feat.head()

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X = df.drop('deposit_flag', axis=1)
y = df['deposit_flag']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [17]:
X.head()

Unnamed: 0  tfl_id  bikes  spaces  total_docks  deposit  \
timestamp                                                                      
2017-06-01 00:00:01          20       1      0      31           31        0   
2017-06-01 00:00:01          52      82     22       0           22       18   
2017-06-01 00:00:01           5      81     25      15           40       25   
2017-06-01 00:00:01          81      80     25      15           40       25   
2017-06-01 00:00:01          39       9      0      24           24      -28   

                     deposit_lag  month  weekday  day  
timestamp                                              
2017-06-01 00:00:01            0      6        4    1  
2017-06-01 00:00:01            4      6        4    1  
2017-06-01 00:00:01            0      6        4    1  
2017-06-01 00:00:01            0      6        4    1  
2017-06-01 00:00:01           28      6        4    1

In [18]:
y.head(2)

timestamp
2017-06-01 00:00:01    0
2017-06-01 00:00:01    1
Name: deposit_flag, dtype: int64

In [19]:
from sklearn.metrics import classification_report, confusion_matrix

In [20]:
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

NameError: name 'pred' is not defined

from sklearn.tree import DecisionTreeClassifier

# print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [22]:
y_test[y_test == 0].count()

8367509

In [23]:
y_train[y_train == 1].count()

6068

In [24]:
X_train.head(2)

Unnamed: 0  tfl_id  bikes  spaces  total_docks  deposit  \
timestamp                                                                      
2017-10-29 14:34:02    10694983      69      8      32           40        0   
2017-12-23 00:36:01    14542391      49     13      27           40        0   

                     deposit_lag  month  weekday  day  
timestamp                                              
2017-10-29 14:34:02            8     10        0   29  
2017-12-23 00:36:01           13     12        6   23

In [27]:
#X = df.drop('deposit_flag', axis=1)

In [28]:
#y = df['deposit_flag']

In [29]:
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [30]:
dtree = DecisionTreeClassifier()

In [31]:
dtree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [32]:
predictions = dtree.predict(X_test)

In [33]:
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

[[8367509       0]
 [      0    2610]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00   8367509
          1       1.00      1.00      1.00      2610

avg / total       1.00      1.00      1.00   8370119



In [34]:
print(predictions)

[0 0 0 ... 0 0 0]


In [35]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

In [36]:
rfc = RandomForestClassifier(n_estimators=200)


In [37]:
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [38]:
rfc_pred = rfc.predict(X_test)

In [39]:
print(confusion_matrix(y_test, rfc_pred))
print(classification_report(y_test, rfc_pred))

[[8367509       0]
 [      0    2610]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00   8367509
          1       1.00      1.00      1.00      2610

avg / total       1.00      1.00      1.00   8370119



In [ ]:
mdl = RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=0)

In [ ]:
mdl.fit(X_train, y_train)

In [ ]:
mdl_pred = mdl.predict(X_test)

In [ ]:
#print(confusion_matrix(y_test, mdl_pred))
#print(classification_report(y_test, mdl_pred))
print(mdl.feature_importances_)

In [ ]:
errors = abs(mdl_pred - y_test)

In [ ]:
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

In [ ]:
print(mdl.predict(mdl_pred))

In [47]:
from sklearn import svm

In [48]:
clf = svm.SVC(gamma=0.001, C=100.)

In [ ]:
clf.fit(X_train, y_train)

In [ ]:
clf.predict(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)

In [ ]:
model.predict(X_test)