In [1]:
import pandas as pd
import numpy as np

In [2]:
ls

176-01-bikelocations.csv     features_ready.csv
176-01-ind_dublinalt.csv     fulldata-spoken.ipynb
176-01-ind_dublinalt.csv.gz  knn for neil.ipynb
176-01-sum_dublinalt.csv     machinestarts.ipynb
PORTOBELLO ROAD.csv          pboh-features.ipynb
f_features.csv               pboh.ipynb


In [3]:
df = pd.read_csv('features_ready.csv', parse_dates=True, index_col='timestamp')

In [4]:
df.head()

Unnamed: 0  bikes  spaces  month  day  weekday  hour  \
timestamp                                                                   
2011-03-02 06:20:02           0      0       0      2    2        3     6   
2011-03-02 06:30:01           1      3      27      2    2        3     6   
2011-03-02 06:40:02           2      3      27      2    2        3     6   
2011-03-02 06:50:01           3      3      27      2    2        3     6   
2011-03-02 07:00:03           4      3      27      2    2        3     7   

                    AMPM  dayofyear  weeknumber  Minute  withdrawal  desposit  
timestamp                                                                      
2011-03-02 06:20:02   AM         61           9      20         0.0       0.0  
2011-03-02 06:30:01   AM         61           9      30         3.0      27.0  
2011-03-02 06:40:02   AM         61           9      40         0.0       0.0  
2011-03-02 06:50:01   AM         61           9      50         0.0       0.0  
2011-03-02 07:00:03   AM         61           9       0         0.0       0.0

In [5]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [6]:

df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1136831 entries, 2011-03-02 06:20:02 to 2018-06-28 16:46:02
Data columns (total 13 columns):
Unnamed: 0    1136831 non-null int64
bikes         1136831 non-null int64
spaces        1136831 non-null int64
month         1136831 non-null int64
day           1136831 non-null int64
weekday       1136831 non-null int64
hour          1136831 non-null int64
AMPM          1136831 non-null object
dayofyear     1136831 non-null int64
weeknumber    1136831 non-null int64
Minute        1136831 non-null int64
withdrawal    1136831 non-null float64
desposit      1136831 non-null float64
dtypes: float64(2), int64(10), object(1)
memory usage: 121.4+ MB


In [7]:
df.tail()

Unnamed: 0  bikes  spaces  month  day  weekday  hour  \
timestamp                                                                   
2018-06-28 16:38:02     1136826      7      23     28   28        4    16   
2018-06-28 16:40:02     1136827      6      24     28   28        4    16   
2018-06-28 16:42:03     1136828      8      22     28   28        4    16   
2018-06-28 16:44:02     1136829      8      22     28   28        4    16   
2018-06-28 16:46:02     1136830      8      22     28   28        4    16   

                    AMPM  dayofyear  weeknumber  Minute  withdrawal  desposit  
timestamp                                                                      
2018-06-28 16:38:02   PM        179          26      38         0.0       0.0  
2018-06-28 16:40:02   PM        179          26      40        -1.0       1.0  
2018-06-28 16:42:03   PM        179          26      42         2.0      -2.0  
2018-06-28 16:44:02   PM        179          26      44         0.0       0.0  
2018-06-28 16:46:02   PM        179          26      46         0.0       0.0

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()

In [11]:
df.head(2)

Unnamed: 0  bikes  spaces  month  day  weekday  hour  \
timestamp                                                                   
2011-03-02 06:20:02           0      0       0      2    2        3     6   
2011-03-02 06:30:01           1      3      27      2    2        3     6   

                    AMPM  dayofyear  weeknumber  Minute  withdrawal  desposit  
timestamp                                                                      
2011-03-02 06:20:02   AM         61           9      20         0.0       0.0  
2011-03-02 06:30:01   AM         61           9      30         3.0      27.0

In [19]:
scaler.fit(df.drop('AMPM', axis=1))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [20]:
scaled_features = scaler.transform(df.drop('AMPM', axis=1))

In [21]:
scaled_features


array([[-1.73204928e+00, -1.35401875e+00, -1.32946160e+00, ...,
        -4.77966784e-01, -6.41391855e-06, -1.75442857e-05],
       [-1.73204624e+00, -1.08525397e+00,  1.08865564e+00, ...,
         9.87869880e-02,  2.73432163e+00,  2.44777994e+01],
       [-1.73204319e+00, -1.08525397e+00,  1.08865564e+00, ...,
         6.75540760e-01, -6.41391855e-06, -1.75442857e-05],
       ...,
       [ 1.73204319e+00, -6.37312683e-01,  6.40856154e-01, ...,
         7.90891515e-01,  1.82287895e+00, -1.81318917e+00],
       [ 1.73204624e+00, -6.37312683e-01,  6.40856154e-01, ...,
         9.06242269e-01, -6.41391855e-06, -1.75442857e-05],
       [ 1.73204928e+00, -6.37312683e-01,  6.40856154e-01, ...,
         1.02159302e+00, -6.41391855e-06, -1.75442857e-05]])

In [22]:
df_feat = pd.DataFrame(scaled_features, columns=df.columns[:-1])

In [23]:
df_feat.head()

Unnamed: 0     bikes    spaces     month       day  weekday      hour  \
0   -1.732049 -1.354019 -1.329462 -1.570037 -1.570037 -0.00106 -0.795203   
1   -1.732046 -1.085254  1.088656 -1.570037 -1.570037 -0.00106 -0.795203   
2   -1.732043 -1.085254  1.088656 -1.570037 -1.570037 -0.00106 -0.795203   
3   -1.732040 -1.085254  1.088656 -1.570037 -1.570037 -0.00106 -0.795203   
4   -1.732037 -1.085254  1.088656 -1.570037 -1.570037 -0.00106 -0.650715   

       AMPM  dayofyear  weeknumber    Minute  withdrawal  
0 -1.108929  -1.097232   -0.477967 -0.000006   -0.000018  
1 -1.108929  -1.097232    0.098787  2.734322   24.477799  
2 -1.108929  -1.097232    0.675541 -0.000006   -0.000018  
3 -1.108929  -1.097232    1.252295 -0.000006   -0.000018  
4 -1.108929  -1.097232   -1.631474 -0.000006   -0.000018

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X = df_feat
y = df['withdrawal']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [26]:
from sklearn.neighbors import KNeighborsClassifier

In [27]:
knn = KNeighborsClassifier(n_neighbors=5)

In [28]:
#need a majority to be able to classify

In [29]:
knn.fit(X_train, y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [30]:
pred = knn.predict(X_test)

In [31]:
pred

array([ 0.,  0.,  1., ...,  0., -1.,  0.])

In [32]:
from sklearn.metrics import classification_report, confusion_matrix

In [33]:
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

[[3 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 5]]
             precision    recall  f1-score   support

      -30.0       0.60      1.00      0.75         3
      -29.0       0.00      0.00      0.00         1
      -28.0       0.00      0.00      0.00         1
      -27.0       0.00      0.00      0.00         0
      -26.0       0.00      0.00      0.00         1
      -25.0       0.00      0.00      0.00         1
      -24.0       0.00      0.00      0.00         2
      -23.0       0.86      1.00      0.93        44
      -22.0       0.73      0.65      0.69        17
      -21.0       0.62      0.67      0.64        12
      -20.0       0.20      0.14      0.17         7
      -19.0       0.76      0.87      0.81        15
      -18.0       0.62      0.50      0.56        10
      -17.0       0.20      0.33      0.25         3
      -16.0       1.00      0.67      0.80         9
      -15.0       0.56      0.6

/Users/neil/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/neil/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [ ]:
error_rate = []

# Will take some time
for i in range(1,4):
    
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    pred_i = knn.predict(X_test)
    error_rate.append(np.mean(pred_i != y_test))

In [ ]:
plt.figure(figsize=(10,6))
plt.plot(range(1,15),error_rate,color='blue', linestyle='dashed', marker='o',
         markerfacecolor='red', markersize=10)
plt.title('Error Rate vs. K Value')
plt.xlabel('K')
plt.ylabel('Error Rate')

from sklearn.tree import DecisionTreeClassifier

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3, metric = 'minkowski', p = 2)

In [ ]:
knn.fit(X_train, y_train)

In [ ]:
pred = knn.predict(X_test)

In [ ]:
pred

In [ ]:
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

In [ ]:
X = df.drop('Style', axis=1)
y = df['Style']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


In [ ]:
knn = KNeighborsClassifier(n_neighbors=5)
    

In [ ]:
knn.fit(X_train, y_train)


In [ ]:
pred = knn.predict(X_test)

In [ ]:
pred


# print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn import neighbors, datasets

n_neighbors = 5

# import some data to play with
h = .02  # step size in the mesh

# Create color maps
cmap_light = ListedColormap(['#FFAAAA', '#AAFFAA', '#AAAAFF', '#AAAABB', '#AAAACC'])
cmap_bold = ListedColormap(['#FF0000', '#00FF00', '#0000FF', '#0000BB', '#0000CC'])

for weights in ['uniform', 'distance']:
    # we create an instance of Neighbours Classifier and fit the data.
    clf = neighbors.KNeighborsClassifier(n_neighbors, weights=weights)
    clf.fit(X, y)

    # Plot the decision boundary. For that, we will assign a color to each
    # point in the mesh [x_min, x_max]x[y_min, y_max].
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                         np.arange(y_min, y_max, h))
    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])

    # Put the result into a color plot
    Z = Z.reshape(xx.shape)
    plt.figure()
    plt.pcolormesh(xx, yy, Z, cmap=cmap_light)

    # Plot also the training points
    plt.scatter(X[:, 0], X[:, 1], c=y, cmap=cmap_bold,
                edgecolor='k', s=20)
    plt.xlim(xx.min(), xx.max())
    plt.ylim(yy.min(), yy.max())
    plt.title("3-Class classification (k = %i, weights = '%s')"
              % (n_neighbors, weights))

plt.show()

In [ ]:
from itertools import product

import numpy as np
import matplotlib.pyplot as plt

from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

In [ ]:
clf2 = KNeighborsClassifier(n_neighbors=7)
clf2.fit(X, y)

In [ ]:
from matplotlib.colors import ListedColormap
from sklearn import neighbors, datasets
h = .02  # step size in the mesh

# Create color maps
cmap_light = ListedColormap(['#FFAAAA', '#AAFFAA', '#AAAAFF'])
cmap_bold = ListedColormap(['#FF0000', '#00FF00', '#0000FF'])
n_neighbors = 15


for weights in ['uniform', 'distance']:
    # we create an instance of Neighbours Classifier and fit the data.
    clf = neighbors.KNeighborsClassifier(n_neighbors, weights=weights)
    clf.fit(X, y)

    # Plot the decision boundary. For that, we will assign a color to each
    # point in the mesh [x_min, x_max]x[y_min, y_max].
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                         np.arange(y_min, y_max, h))
    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])

    # Put the result into a color plot
    Z = Z.reshape(xx.shape)
    plt.figure()
    plt.pcolormesh(xx, yy, Z, cmap=cmap_light)

    # Plot also the training points
    plt.scatter(X[:, 0], X[:, 1], c=y, cmap=cmap_bold,
                edgecolor='k', s=20)
    plt.xlim(xx.min(), xx.max())
    plt.ylim(yy.min(), yy.max())
    plt.title("3-Class classification (k = %i, weights = '%s')"
              % (n_neighbors, weights))

plt.show()

In [ ]:

import itertools
import numpy as np
import matplotlib.pyplot as plt

from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [ ]:
df.columns

In [ ]:
y_pred = knn.fit(X_train, y_train).predict(X_test)
class_names = df.columns

def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

# Compute confusion matrix
cnf_matrix = confusion_matrix(y_test, y_pred)
np.set_printoptions(precision=3)

# Plot non-normalized confusion matrix
plt.figure()
plot_confusion_matrix(cnf_matrix, classes=class_names,
                      title='Confusion matrix, without normalization')

# Plot normalized confusion matrix
plt.figure()
plot_confusion_matrix(cnf_matrix, classes=class_names, normalize=True,
                      title='Normalized confusion matrix')

plt.show()

In [ ]:
import seaborn as sns

ax= plt.subplot()
sns.heatmap(cm, annot=True, ax = ax); #annot=True to annotate cells

# labels, title and ticks
ax.set_xlabel('Predicted labels');ax.set_ylabel('True labels'); 
ax.set_title('Confusion Matrix'); 
ax.xaxis.set_ticklabels(['business', 'health']); ax.yaxis.set_ticklabels(['health', 'business']);

In [35]:
df.head()

Unnamed: 0  bikes  spaces  month  day  weekday  hour  \
timestamp                                                                   
2011-03-02 06:20:02           0      0       0      2    2        3     6   
2011-03-02 06:30:01           1      3      27      2    2        3     6   
2011-03-02 06:40:02           2      3      27      2    2        3     6   
2011-03-02 06:50:01           3      3      27      2    2        3     6   
2011-03-02 07:00:03           4      3      27      2    2        3     7   

                    AMPM  dayofyear  weeknumber  Minute  withdrawal  desposit  
timestamp                                                                      
2011-03-02 06:20:02   AM         61           9      20         0.0       0.0  
2011-03-02 06:30:01   AM         61           9      30         3.0      27.0  
2011-03-02 06:40:02   AM         61           9      40         0.0       0.0  
2011-03-02 06:50:01   AM         61           9      50         0.0       0.0  
2011-03-02 07:00:03   AM         61           9       0         0.0       0.0

In [36]:
%load_ext jupyternotify

<IPython.core.display.Javascript object>

In [37]:
%%notify
import time
time.sleep(5)

<IPython.core.display.Javascript object>

In [38]:
%%notify -o
answer = 42
'The answer is {}.'.format(answer)

'The answer is 42.'

<IPython.core.display.Javascript object>